# Псевдо yaml
# Если образ требуется собирать на лету, вместо использования готового, используем build

# Можно указывать версию compose
# Во второй версии link меняется на depends_on
# В третьей версии добавлена поддержка docker swarm
version: 2

redis:
  image: redis
  networks:
  - backend

db:
  image: postgres:9.4
  networks:
  - backend

vote:
  build: ./vote
  ports:
  - 5000:80
  links:
  - redis
  networks:
  - frontend
  - backend

result:
  build: ./result
  ports:
  - 5001:80
  links:
  - db
  networks:
  - frontend
  - backend

worker:
  build: ./worker
  links:
  - db
  - redis
  networks:
  - backend

networks:
  frontend:
  backend: